57 login register redesign
CSCI3308-Group7-Book-Tracker/book-tracker pull request #60
Opened 2023-11-16 00:19 UTC by ibrahimdul

2023-11-16 01:30 UTC, rlodhicode requested changes
Look into code comments left on files.

2023-11-16 01:30 UTC, rlodhicode commented on Project-Code/src/views/pages/login.ejs
We need to ensure a couple things here.
One, the Back buttons should hold the class btn-secondary instead of btn-primary as well. 
We also want these buttons to be equally spaced horizontally and equally sized(You can do this by using bootstrap rows and cols, and some styling to ensure button size and length is the same). 
The onclick feature should not be used to redirect on the back buttons (during testing I found that this redirect doesn't seem to work).
Last thing is more aesthetic, we should make the entire text "Not a User? Sign Up!" to be an a tag, just use some styling components to make the link color grey and slightly transparent. (Sorry I could have been more specific in my acceptance criteria...)

2023-11-16 01:30 UTC, rlodhicode commented on Project-Code/src/views/pages/register.ejs
We need to make the same changes here, the only different being the link text "Already Registered? Log In!"

2023-11-29 22:41 UTC, rlodhicode requested changes
Just for code clarity here are a couple notes I found. As of now, we still need to figure out how to service static files (.css, .jpg, etc...) with the express application framework. This is why in the welcome.ejs page you will see a style block before the html code. Because technically the welcome.css file does nothing right now :/

Anyways, it looks like you didn't add a link tag that would link this welcome.css page into the login.ejs page. So the btn-block class you created is essentially doing nothing (At least that would be the expected behavior). What I would do is remove the btn-block class from the welcome.css page and from the login.ejs and register.ejs page, and test to see if the rendered page is what you expected it to be.

In the future as well, we should try to keep some code clarity. If we do end up figuring out how to get our css and img files working, I would recommend creating your own css file unless appending to an existing one makes sense. In my mind, the welcome.css file should ideally only house the styling components needed for the welcome.ejs page. But that doesn't matter too too much. Also, feel free to click the Resolve conversation button on the previous reviews when you believe that you have addressed them.

2023-11-29 23:01 UTC, ibrahimdul commented
I think that the pull I did now solve the issue

2023-11-29 23:02 UTC, ibrahimdul reviewed
here is the last one

2023-11-29 23:07 UTC, rlodhicode approved these changes
Looks a lot better.

2023-11-30 18:47 UTC, merged